[package]
name = "metamorph"
version = "0.1.0"
edition = "2021"
description = "A playground for graph transformations"
repository = "https://github.com/MylesWritesCode/rust-wasm"
license = "MIT"

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
lto = true
opt-level = 3
codegen-units = 1

[dependencies]
wasm-bindgen = "0.2.93"
graph = { path = "../graph" }
serde-wasm-bindgen = "0.6.5"
serde = { version = "1.0.209", features = ["derive"] }
getrandom = { version = "0.2", features = ["js"] }
